In [1]:
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1.shape)   # (5,)
print(arr2.shape)   # (2,3)


(5,)
(2, 3)


In [21]:
np.zeros((2,3))      # 2x3 array of zeros
np.ones((3,3))       # 3x3 array of ones
np.arange(0,10,2) 
# [0, 2, 4, 6, 8]
print(np.linspace(0,1,6)  ) # [0. ,0.25,0.5,0.75,1.]
np.random.rand(2,2)  # random 2x2 array (0–1) 
np.random.randint(1,2,(3,3)) # random ints 1–9


[0.  0.2 0.4 0.6 0.8 1. ]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [22]:
arr = np.array([10,20,30,40,50])
print(arr[0])     # 10
print(arr[-1])    # 50
print(arr[1:4])   # [20,30,40]

mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[0,2])   # element at row=0, col=2 → 3
print(mat[:,1])   # second column → [2,5,8]
print(mat[1,:])   # second row → [4,5,6]


10
50
[20 30 40]
3
[2 5 8]
[4 5 6]


In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)     # [5 7 9]
print(a * b)     # [4 10 18]
print(a ** 2)    # [1 4 9]
print(np.sqrt(b))# [2. 2.236 2.449]


[5 7 9]
[ 4 10 18]
[1 4 9]
[2.         2.23606798 2.44948974]


In [24]:
arr = np.array([1,2,3,4,5,6])

print(arr.mean())     # 3.5
print(arr.sum())      # 21
print(arr.max())      # 6
print(arr.min())      # 1
print(arr.std())      # standard deviation


3.5
21
6
1
1.707825127659933


In [26]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A.dot(B))        # matrix multiplication
print(np.linalg.inv(A)) # inverse of A
print(np.linalg.det(A)) # determinant of A


[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [27]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25])     # [30 40 50]
print(arr[arr % 20 == 0])# [20 40]


[30 40 50]
[20 40]


In [28]:
# Reshaping arrays
import numpy as np

arr = np.arange(12)   # [0 1 2 3 4 5 6 7 8 9 10 11]
print(arr.shape)      # (12,)

# Reshape into 3x4 matrix
mat = arr.reshape(3,4)
print(mat)


(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
arr.reshape(-1, 6)   # -1 lets NumPy figure out dimension automatically


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [30]:
arr = np.array([1, 2, 3])
print(arr + 10)   # [11 12 13]
print(arr * 2)    # [2 4 6]
print(arr ** 2)   # [1 4 9]

[11 12 13]
[2 4 6]
[1 4 9]


In [31]:

a = np.array([[1],[2],[3]])   # shape (3,1)
b = np.array([10,20,30])      # shape (3,)
print(a + b)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [1]:
import numpy as np

print(np.random.rand(3))       # 3 random floats (0–1)
print(np.random.randint(1,10)) # single random int 1–9
print(np.random.randint(1,10, size=5)) # 5 random ints 1–9


[0.41415908 0.87030012 0.91556368]
3
[9 6 9 4 9]


In [2]:
# Simulate 10 dice rolls (1–6)
dice = np.random.randint(1, 7, 10)
print(dice)


[6 6 2 2 3 1 6 5 1 1]


In [6]:
N = 100000

x = np.random.rand(N)
y = np.random.rand(N)

inside_circle = (x**2 + y**2) <= 1
pi_estimate = (inside_circle.sum() / N) * 4
print("Estimated Pi:", pi_estimate)


Estimated Pi: 3.1444


In [7]:
colors = ["Red", "Blue", "Green"]
print(np.random.choice(colors, size=5))   # pick 5 random colors


['Blue' 'Red' 'Blue' 'Green' 'Blue']


In [8]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A @ B)       # matrix multiplication (preferred)
print(np.dot(A, B)) # same thing


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [9]:
np.linalg.det(A)


-2.0000000000000004

In [10]:
vals, vecs = np.linalg.eig(A)
print("Eigenvalues:", vals)
print("Eigenvectors:\n", vecs)


Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [13]:
A = np.array([[2, 1], [1, -1]])
B = np.array([5, 1])

X = np.linalg.solve(A,B)
print("Solution:", X)


Solution: [2. 1.]


In [14]:
import numpy as np, time

arr = np.arange(1_000_000)

# Python loop
start = time.time()
total = sum([x**2 for x in arr])
print("Loop:", time.time()-start)

# NumPy vectorized
start = time.time()
total = np.sum(arr**2)
print("NumPy:", time.time()-start)


Loop: 0.6694977283477783
NumPy: 0.0008068084716796875


C:\Users\ertan\AppData\Local\Temp\ipykernel_6988\3164889563.py:7: RuntimeWarning: overflow encountered in scalar add
  total = sum([x**2 for x in arr])


In [19]:
N = 1000
dice1 = np.random.randint(1,7,N)
dice2 = np.random.randint(1,7,N)

prob = np.mean((dice1 + dice2) == 7)
print("P(sum=7):", prob)   # ~0.1666 (1/6)


P(sum=7): 0.153


In [20]:
winning = set(np.random.choice(np.arange(1,50), 6, replace=False))
ticket = set(np.random.choice(np.arange(1,50), 6, replace=False))

print("Winning numbers:", winning)
print("Your ticket:", ticket)
print("Matches:", len(winning & ticket))


Winning numbers: {35, 40, 43, 20, 27, 30}
Your ticket: {48, 20, 26, 27, 30, 31}
Matches: 3
