In [8]:
import numpy as np
import sys
import time

# 1 million numbers
N = 1_000_000

# Python list
py_list = list(range(N))

# NumPy array
np_array = np.arange(N)

# Memory usage
print("Python list size:", sys.getsizeof(py_list), "bytes")  
print("NumPy array size:", np_array.nbytes, "bytes")

# Timing adding 1 to each element
start = time.time()
py_list = [x + 1 for x in py_list]
end = time.time()
print("Python list time:", end - start, "seconds")

start = time.time()
np_array = np_array + 1
end = time.time()
print("NumPy array time:", end - start, "seconds")


Python list size: 8000056 bytes
NumPy array size: 4000000 bytes
Python list time: 0.05597209930419922 seconds
NumPy array time: 0.0 seconds


In [9]:
numbers = [10, 20, 30, 40]
print(numbers[1:3])  # [20, 30]


[20, 30]


In [10]:
arr = np.array([10, 20, 30, 40])
print(arr[1:3])      # array([20, 30])
print(arr[::2])      # array([10, 30])  <-- step slicing


[20 30]
[10 30]


In [11]:
arr = np.array([10, 20, 30, 40])
sub = arr[1:3]
sub[0] = 999
print(arr)  # [ 10 999  30  40 ]


[ 10 999  30  40]


In [12]:
import numpy as np

# Create array 0–9
arr = np.arange(10)

# Slice from index 2 to 5 (5 is exclusive)
arr[0:10] = -1

print(arr)


[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]


In [13]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Condition: elements > 25
mask = arr > 25
print(mask)  # array([False, False,  True,  True,  True])

# Apply the mask
print(arr[mask])  # array([30, 40, 50])


[False False  True  True  True]
[30 40 50]


In [14]:
print(arr[arr > 25])  # array([30, 40, 50])


[30 40 50]


In [15]:
# Elements > 15 and < 45
print(arr[(arr > 15) & (arr < 45)])  # array([20, 30, 40])

# Elements < 15 or > 45
print(arr[(arr < 15) | (arr > 45)])  # array([10, 50])


[20 30 40]
[10 50]


In [16]:
arr[arr > 25] = 999
print(arr)  # array([ 10,  20, 999, 999, 999])


[ 10  20 999 999 999]


In [17]:
arr1 = np.arange(20)

arr1[arr1 % 2 == 0] = -1

print(arr1)  # array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9, -1, 11, -1, 13, -1, 15, -1, 17, -1, 19])

[-1  1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19]


In [18]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr + 10)  # [11 12 13]


[11 12 13]


In [19]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(A + b)


[[11 22 33]
 [14 25 36]]


In [20]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

c = np.array([[10],
              [20]])

print(A + c)


[[11 12 13]
 [24 25 26]]


In [21]:
arr2 = np.array([[1, 2, 3],
         [4, 5, 6],[7,8,9]])

arr3 = np.array([[100],[200],[300]])

print(arr2 + arr3)  # array([[101, 102, 103], [204, 205, 206], [307, 308, 309]])


[[101 102 103]
 [204 205 206]
 [307 308 309]]


In [22]:
import numpy as np

# Create 3x3 array 1–9
A = np.arange(1, 10).reshape(3, 3)
print("Original A:\n", A)

# 1️⃣ Add [10, 20, 30] to each row (broadcast across columns)
row_add = np.array([10, 20, 30])
result_rows = A + row_add
print("\nAfter adding to rows:\n", result_rows)

# 2️⃣ Add [100, 200, 300] as a column (broadcast down the rows)
col_add = np.array([[100], [200], [300]])
result_cols = A + col_add
print("\nAfter adding to columns:\n", result_cols)


Original A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

After adding to rows:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

After adding to columns:
 [[101 102 103]
 [204 205 206]
 [307 308 309]]


In [23]:
import numpy as np
import time

x = np.arange(1_000_000)

start = time.time()
y_loop = np.zeros_like(x)
for i in range(len(x)):
    y_loop[i] = 3*x[i]**2 + 2*x[i] + 1
end = time.time()
print("Loop time:", end - start, "sec")


C:\Users\ertan\AppData\Local\Temp\ipykernel_5492\3948597444.py:9: RuntimeWarning: overflow encountered in scalar multiply
  y_loop[i] = 3*x[i]**2 + 2*x[i] + 1
C:\Users\ertan\AppData\Local\Temp\ipykernel_5492\3948597444.py:9: RuntimeWarning: overflow encountered in scalar add
  y_loop[i] = 3*x[i]**2 + 2*x[i] + 1


Loop time: 0.7631330490112305 sec


In [24]:
start = time.time()
y_vec = 3*x**2 + 2*x + 1
end = time.time()
print("Vectorized time:", end - start, "sec")


Vectorized time: 0.0060634613037109375 sec


In [ ]:
import pandas as pd


df = pd.read_excel(
    "C:/Users/ertan/sem 5 ki backchodi/important notes/Superstore Sales 🛒🏷️🛍️📦🏪 export 2025-08-16 14-30-51.xlsx",
    engine="openpyxl"
)

print(df.shape)
print(df.head())
print(df.info())


FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/ertan/sem 5 ki backchodi/important notes/Superstore Sales 🛒🏷️🛍️📦🏪 export 2025-08-16 14-30-51.xlsx'

: 